### ISSUE TITLE
 Send UpstreamSegment to collector fail with a grpc internal exception.  

### ISSUE THREAD

**Issue by qw2283345** [OpenSkywalking/skywalking#493]
按照教程部署探针
启动后报错

我的程序是spring boot
启动参数如下
` java 
      -javaagent:/skywalking/skywalking-agent.jar
      -Dconfig=/skywalking/
      -Xms10m
      -Xmx80m
      -Djava.security.egd=file:/dev/./urandom
      -Dspring.profiles.active=test
      -Dserver.port=9000
      -jar
      - /test-1.0-SNAPSHOT.jar
       `

`ERROR 2017-10-10 11:19:28 TraceSegmentServiceClient :  Send UpstreamSegment to collector fail with a grpc internal exception.
org.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNAVAILABLE
        at org.skywalking.apm.dependencies.io.grpc.Status.asRuntimeException(Status.java:543)
        at org.skywalking.apm.dependencies.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:395)
        at org.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
        at org.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
        at org.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:512)
        at org.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:429)
        at org.skywalking.apm.dependencies.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:544)
        at org.skywalking.apm.dependencies.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
        at org.skywalking.apm.dependencies.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.skywalking.apm.dependencies.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /0.0.0.0:11800
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.skywalking.apm.dependencies.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:352)
        at org.skywalking.apm.dependencies.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        at org.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
        at org.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at org.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at org.skywalking.apm.dependencies.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at org.skywalking.apm.dependencies.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at org.skywalking.apm.dependencies.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        ... 1 more
Caused by: java.net.ConnectException: Connection refused
        ... 11 more `

**Comment by wu-sheng** [comment]
Collector是否已经正常启动？从日志看来，服务端启动好像出现了问题。

**Comment by qw2283345** [comment]
查看了控制台，Collector启动正常，我是以docker形式运行Collector的，docker-compose.yml示例里有3个端口，collector.servers 这个是指向哪个端口为准的？会不会是这个问题？

**Comment by wu-sheng** [comment]
Docker compose中配置的内容，默认只有在本地运行时有效。如果你要连接远程，可以联系下 @ascrutae ,或者独立部署下Collector。

**Comment by qw2283345** [comment]
好的，我先试一下独立部署Collector，再看看问题如果，然后可以了话，再尝试用docker，感谢回答

**Comment by ascrutae** [comment]
@qw2283345  你的collector和应用是部署在两台机器上还是部署在两台机器上？

**Comment by qw2283345** [comment]
@ascrutae 你好，collector和应用都是同一台机器上的

**Comment by wu-sheng** [comment]
@qw2283345 独立部署Collector是否能够正常工作？

**Comment by qw2283345** [comment]
@wu-sheng 独立部署已经可以了，谢谢

**Comment by wu-sheng** [comment]
@qw2283345 好的，我将保留这个issue处于open状态，方便讨论容器化启动的问题。cc @ascrutae

**Comment by qw2283345** [comment]
@acurtain 请问
`environment:
      - ZK_ADDRESSES=zookeeper-server:2181
      - ES_ADDRESSES=es-server:9300
      - BIND_HOST=0.0.0.0
      - UI_BIND_HOST=skywalking-collector
      - CLUSTER_BIND_HOST=0.0.0.0`
BIND_HOST、CLUSTER_BIND_HOST 代表什么，一定要填0.0.0.0 ？绑定的地址IP吗
意思是否对应着 skywalking-collector程序的config/application.yml
`agent_server:
  jetty:
    host: localhost
    # The port used
    port: 10800
    context_path: /
agent_stream:
  grpc:
    host: localhost
    port: 11800
  jetty:
    host: localhost
    port: 12800
    context_path: /
ui:
  jetty:
    host: localhost
    port: 12800
    context_path: /
collector_inside:
  grpc:
    host: localhost
    port: 11800`
的host地址IP?

**Comment by wu-sheng** [comment]
@qw2283345 因为容器内外的ip是不同的，而探针会通过HTTP接口进行服务查找，然后返回gRPC地址，进行数据通讯。

**Comment by qw2283345** [comment]
@wu-sheng @ascrutae 现在的这个docker-compose.yml文件配置上是有问题的，
BIND_HOST、CLUSTER_BIND_HOST 这些地址填了0.0.0.0的话，探针会访问不了0.0.0.0:11800，如果绑定宿主机IP的话，但是程序又报错不允许的，所以得把docker网络模式改成host并设置extra_hosts指向zk、es

**Comment by ascrutae** [comment]
@qw2283345  因为在启动的时候把所有端口全部都映射出来，并且宿主机和镜像是在同一台机器上，所以访问是没有问题的。

**Comment by wu-sheng** [comment]
@qw2283345 要确定下的是，绑定0.0.0.0是不是在你的机器上是不允许的。

**Comment by qw2283345** [comment]
@wu-sheng @ascrutae 绑定0.0.0.0是可以的，没有问题的，可以正常启动的，但是当其它探针也是docker程序的时候，就无法访问0.0.0.0:11800了，就会访问不了

**Comment by wu-sheng** [comment]
@qw2283345 我们目前提供默认配置是认为你的应用在本机非容器化启动。所以可能还不太符合你的场景。目前docker的这个特性比较麻烦。

**Comment by wu-sheng** [comment]
问题已解决，关闭issue。
