### ISSUE TITLE
agent error issue====>error log:  Failed to enhance class org.apache.catalina.core.StandardWrapperValve java.lang.IllegalStateException: Already implemented interface interface 

### ISSUE THREAD

**Issue by wwwjljj** [OpenSkywalking/skywalking#512]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
skywalking-agent3.2.2.jar

### What version of your OS?
debian 7 ( x64)

### What version of your JRE?
java 7
JDK
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)

### What company or project?
beijing dkd com .  project: wap

### What did you do?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

When I  start agent , a lot of error logs occured like below , and nothing display on the ui web.Please solve this problem.
### ERROR 1:

DEBUG 2017-10-12 23:34:44 SkyWalkingAgent :  Finish the prepare stage for org.apache.catalina.core.StandardWrapperValve.
ERROR 2017-10-12 23:34:44 SkyWalkingAgent :  Failed to enhance class org.apache.catalina.core.StandardWrapperValve
java.lang.IllegalStateException: Already implemented interface interface org.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance for class org.apache.catalina.core.StandardWrapperValve
    at org.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.InstrumentedType$Default.validated(InstrumentedType.java:766)
    at org.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:465)
    at org.skywalking.apm.dependencies.net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:176)
    at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:8902)
    at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:9303)
    at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9266)
    at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1300(AgentBuilder.java:9044)
    at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9622)
at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:9572)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:9191)
    at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
    at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
............

### ERROR 2:
DEBUG 2017-10-12 23:34:54 SkyWalkingAgent :  Finish the prepare stage for com.pitaya.daokoudai.wap.channel.ChannelController.
ERROR 2017-10-12 23:34:54 SkyWalkingAgent :  Failed to enhance class com.orange.beijingqianhai.wap.channel.ChannelController
java.lang.IllegalStateException: Cannot resolve type description for com.orange.beijingqianhai.wap.channel.ChannelController$auxiliary$J3Bf3LDE
    at org.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:134)
    at org.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1257)
    at org.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getModifiers(TypeDescription.java:7046)
    at org.skywalking.apm.dependencies.net.bytebuddy.description.ModifierReviewable$AbstractBase.matchesMask(ModifierReviewable.java:539)
    at org.skywalking.apm.dependencies.net.bytebuddy.description.ModifierReviewable$AbstractBase.isPublic(ModifierReviewable.java:313)
    at org.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDescription$AbstractBase.isVisibleTo(TypeDescription.java:6699)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:31)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:12)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:29)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:33)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:14)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.MethodParameterTypeMatcher.matches(MethodParameterTypeMatcher.java:31)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.MethodParameterTypeMatcher.matches(MethodParameterTypeMatcher.java:12)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.CollectionItemMatcher.matches(CollectionItemMatcher.java:31)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.CollectionItemMatcher.matches(CollectionItemMatcher.java:11)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:29)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.MethodParametersMatcher.matches(MethodParametersMatcher.java:32)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.MethodParametersMatcher.matches(MethodParametersMatcher.java:13)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:101)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:101)
.......

### ERROR3 
Failed to enhance class redis.clients.jedis.Jedis
java.lang.IllegalStateException: Cannot resolve type description for redis.clients.jedis.Jedis$auxiliary$8AfM6H52
    at org.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:134)
    at org.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1257)
    at org.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getModifiers(TypeDescription.java:7046)
    at org.skywalking.apm.dependencies.net.bytebuddy.description.ModifierReviewable$AbstractBase.matchesMask(ModifierReviewable.java:539)
    at org.skywalking.apm.dependencies.net.bytebuddy.description.ModifierReviewable$AbstractBase.isPublic(ModifierReviewable.java:313)
    at org.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDescription$AbstractBase.isVisibleTo(TypeDescription.java:6699)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:31)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:12)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:29)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:33)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:14)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.MethodParameterTypeMatcher.matches(MethodParameterTypeMatcher.java:31)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.MethodParameterTypeMatcher.matches(MethodParameterTypeMatcher.java:12)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.CollectionItemMatcher.matches(CollectionItemMatcher.java:31)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.CollectionItemMatcher.matches(CollectionItemMatcher.java:11)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:29)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.MethodParametersMatcher.matches(MethodParametersMatcher.java:32)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.MethodParametersMatcher.matches(MethodParametersMatcher.java:13)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:101)
    at org.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:101)

**Comment by wu-sheng** [comment]
@wwwjljj We still need your dependency libs. Run `mvn dependency:tree` in your project root dictionary.

**Comment by wu-sheng** [comment]
@ascrutae  

> DEBUG 2017-10-12 23:34:44 SkyWalkingAgent : Finish the prepare stage for org.apache.catalina.core.StandardWrapperValve.
ERROR 2017-10-12 23:34:44 SkyWalkingAgent : Failed to enhance class org.apache.catalina.core.StandardWrapperValve
java.lang.IllegalStateException: Already implemented interface interface org.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance for class org.apache.catalina.core.StandardWrapperValve

I think this is the high priority error. Although in 3.2.3, supported enhancing single class more than once, but this shouldn't happen in `org.apache.catalina.core.StandardWrapperValve`, right?

**Comment by wwwjljj** [comment]
@wu-sheng 
mvn dependency:tree  command results:

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building bjqianhai-wap 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://domainxxx/nexus/content/groups/public/com/orange/bjqianhai/base-framework/0.0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://domainxxx/nexus/content/groups/public/com/orange/bjqianhai/bjqianhai-service/0.0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://domainxxx/nexus/content/groups/public/com/orange/bjqianhai/bjqianhai-model/0.0.1-SNAPSHOT/maven-metadata.xml
Downloaded: http://domainxxx/nexus/content/groups/public/com/orange/bjqianhai/bjqianhai-model/0.0.1-SNAPSHOT/maven-metadata.xml (788 B at 8.5 KB/sec)
Downloading: http://domainxxx/nexus/content/groups/public/com/orange/bjqianhai/base-common-service/0.0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://domainxxx/nexus/content/groups/public/com/orange/bjqianhai/base-business-service/0.0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://domainxxx/nexus/content/groups/public/com/orange/bjqianhai/base-capital-service/0.0.1-SNAPSHOT/maven-metadata.xml
Downloading: http://domainxxx/nexus/content/groups/public/com/orange/bjqianhai/bjqianhai-plan-model/0.0.1-SNAPSHOT/maven-metadata.xml
Downloaded: http://domainxxx/nexus/content/groups/public/com/orange/bjqianhai/bjqianhai-plan-model/0.0.1-SNAPSHOT/maven-metadata.xml (793 B at 14.1 KB/sec)
Downloading: http://domainxxx/nexus/content/groups/public/com/orange/bjqianhai/testing/0.0.1-SNAPSHOT/maven-metadata.xml
[INFO]
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ bjqianhai-wap ---
[INFO] com.orange.bjqianhai:bjqianhai-wap:war:0.0.1-SNAPSHOT
[INFO] +- com.orange.bjqianhai:base-framework:jar:0.0.1-SNAPSHOT:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.1:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.3:compile
[INFO] |  |  \- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  +- com.google.zxing:core:jar:3.0.0:compile
[INFO] |  +- com.google.zxing:javase:jar:3.0.0:compile
[INFO] |  +- com.googlecode.xmemcached:xmemcached:jar:2.0.0:compile
[INFO] |  +- net.spy:spymemcached:jar:2.12.0:compile
[INFO] |  +- com.whalin:Memcached-Java-Client:jar:3.0.1:compile
[INFO] |  +- io.netty:netty-all:jar:4.0.36.Final:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.7:compile
[INFO] |  +- commons-configuration:commons-configuration:jar:1.10:compile
[INFO] |  |  \- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  +- org.springframework:spring-core:jar:4.0.5.RELEASE:compile
[INFO] |  +- org.springframework:spring-web:jar:4.0.5.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-beans:jar:4.0.5.RELEASE:compile
[INFO] |  +- org.springframework:spring-orm:jar:4.0.5.RELEASE:compile
[INFO] |  +- org.springframework:spring-jdbc:jar:4.0.5.RELEASE:compile
[INFO] |  +- org.springframework:spring-context:jar:4.0.5.RELEASE:compile
[INFO] |  +- org.springframework:spring-aop:jar:4.0.5.RELEASE:compile
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  +- org.springframework:spring-expression:jar:4.0.5.RELEASE:compile
[INFO] |  +- org.springframework:spring-test:jar:4.0.5.RELEASE:compile
[INFO] |  +- org.springframework:spring-tx:jar:4.0.5.RELEASE:compile
[INFO] |  +- org.springframework:spring-webmvc:jar:4.0.5.RELEASE:compile
[INFO] |  +- org.springframework.integration:spring-integration-mail:jar:4.0.2.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-context-support:jar:4.0.5.RELEASE:compile
[INFO] |  |  \- org.springframework.integration:spring-integration-core:jar:4.0.2.RELEASE:compile
[INFO] |  |     \- org.springframework:spring-messaging:jar:4.0.5.RELEASE:compile
[INFO] |  +- org.apache.velocity:velocity:jar:1.7:compile
[INFO] |  +- opensymphony:sitemesh:jar:2.4.2:compile
[INFO] |  +- taglibs:standard:jar:1.1.2:compile
[INFO] |  +- ognl:ognl:jar:3.0.8:compile
[INFO] |  +- javax.servlet:jstl:jar:1.2:compile
[INFO] |  +- javax.transaction:jta:jar:1.0.1B:compile
[INFO] |  +- net.sf.json-lib:json-lib:jar:jdk15:2.3:compile
[INFO] |  |  \- net.sf.ezmorph:ezmorph:jar:1.0.6:compile
[INFO] |  +- org.jdom:jdom:jar:1.1:compile
[INFO] |  +- javassist:javassist:jar:3.12.1.GA:compile
[INFO] |  +- org.freemarker:freemarker:jar:2.3.20:compile
[INFO] |  +- net.sf.ehcache:ehcache:jar:1.2.3:compile
[INFO] |  +- dom4j:dom4j:jar:1.6.1:compile
[INFO] |  |  \- xml-apis:xml-apis:jar:1.0.b2:compile
[INFO] |  +- commons-beanutils:commons-beanutils:jar:1.9.2:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.9:compile
[INFO] |  +- commons-collections:commons-collections:jar:3.2.1:compile
[INFO] |  +- commons-dbcp:commons-dbcp:jar:1.4:compile
[INFO] |  +- commons-fileupload:commons-fileupload:jar:1.3.1:compile
[INFO] |  +- commons-httpclient:commons-httpclient:jar:3.1:compile
[INFO] |  +- commons-io:commons-io:jar:2.4:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.0:compile
[INFO] |  +- commons-logging:commons-logging-api:jar:1.1:compile
[INFO] |  +- commons-pool:commons-pool:jar:1.6:compile
[INFO] |  +- commons-validator:commons-validator:jar:1.4.0:compile
[INFO] |  |  \- commons-digester:commons-digester:jar:1.8:compile
[INFO] |  +- cglib:cglib-nodep:jar:3.1:compile
[INFO] |  +- c3p0:c3p0:jar:0.9.1.2:compile
[INFO] |  +- org.beanshell:bsh:jar:2.0b5:compile
[INFO] |  +- org.aspectj:aspectjrt:jar:1.8.0:compile
[INFO] |  +- org.aspectj:aspectjweaver:jar:1.8.0:compile
[INFO] |  +- org.hibernate:hibernate-core:jar:3.6.10.Final:compile
[INFO] |  |  \- org.hibernate.javax.persistence:hibernate-jpa-2.0-api:jar:1.0.1.Final:compile
[INFO] |  +- org.hibernate:hibernate-commons-annotations:jar:3.2.0.Final:compile
[INFO] |  +- org.apache.logging.log4j:log4j-1.2-api:jar:2.5:compile
[INFO] |  +- org.apache.logging.log4j:log4j-core:jar:2.5:compile
[INFO] |  +- org.apache.logging.log4j:log4j-api:jar:2.5:compile
[INFO] |  +- org.apache.logging.log4j:log4j-slf4j-impl:jar:2.5:compile
[INFO] |  +- org.apache.logging.log4j:log4j-jcl:jar:2.5:compile
[INFO] |  +- org.apache.logging.log4j:log4j-jul:jar:2.5:compile
[INFO] |  +- org.apache.logging.log4j:log4j-web:jar:2.5:runtime
[INFO] |  +- org.json:org.json:jar:chargebee-1.0:compile
[INFO] |  +- antlr:antlr:jar:2.7.7:compile
[INFO] |  +- com.google.code.kaptcha:kaptcha:jar:2.3.2:compile
[INFO] |  +- javax.mail:mail:jar:1.4.7:compile
[INFO] |  |  \- javax.activation:activation:jar:1.1:compile
[INFO] |  +- org.apache.ant:ant:jar:1.7.0:compile
[INFO] |  |  \- org.apache.ant:ant-launcher:jar:1.7.0:compile
[INFO] |  +- org.apache.struts:struts2-core:jar:2.3.16.3:compile
[INFO] |  |  \- org.apache.struts.xwork:xwork-core:jar:2.3.16.3:compile
[INFO] |  |     +- asm:asm:jar:3.3:compile
[INFO] |  |     \- asm:asm-commons:jar:3.3:compile
[INFO] |  |        \- asm:asm-tree:jar:3.3:compile
[INFO] |  +- org.apache.struts:struts2-spring-plugin:jar:2.3.16.3:compile
[INFO] |  +- org.apache.struts:struts2-json-plugin:jar:2.3.16.3:compile
[INFO] |  +- jaxen:jaxen:jar:1.1.6:compile
[INFO] |  +- org.springframework.batch:spring-batch-core:jar:3.0.0.RELEASE:compile
[INFO] |  |  +- com.ibm.jbatch:com.ibm.jbatch-tck-spi:jar:1.0:compile
[INFO] |  |  |  \- javax.batch:javax.batch-api:jar:1.0:compile
[INFO] |  |  +- com.thoughtworks.xstream:xstream:jar:1.4.7:compile
[INFO] |  |  |  +- xmlpull:xmlpull:jar:1.1.3.1:compile
[INFO] |  |  |  \- xpp3:xpp3_min:jar:1.1.4c:compile
[INFO] |  |  \- org.codehaus.jettison:jettison:jar:1.2:compile
[INFO] |  +- org.springframework.batch:spring-batch-infrastructure:jar:3.0.0.RELEASE:compile
[INFO] |  +- org.springframework.retry:spring-retry:jar:1.1.0.RELEASE:compile
[INFO] |  +- org.quartz-scheduler:quartz:jar:2.2.1:compile
[INFO] |  +- org.quartz-scheduler:quartz-jobs:jar:2.2.1:compile
[INFO] |  +- org.quartz-scheduler:quartz-oracle:jar:2.1.7:compile
[INFO] |  +- org.quartz-scheduler:quartz-jboss:jar:2.1.7:compile
[INFO] |  +- net.sourceforge.pjl-comp-filter:pjl-comp-filter:jar:1.7:compile
[INFO] |  +- commons-net:commons-net:jar:ftp:3.3:compile
[INFO] |  +- com.belerweb:pinyin4j:jar:2.5.0:compile
[INFO] |  +- eu.bitwalker:UserAgentUtils:jar:1.17:compile
[INFO] |  +- org.apache.poi:poi:jar:3.14:compile
[INFO] |  +- org.apache.poi:poi-ooxml:jar:3.14:compile
[INFO] |  |  +- org.apache.poi:poi-ooxml-schemas:jar:3.14:compile
[INFO] |  |  |  \- org.apache.xmlbeans:xmlbeans:jar:2.6.0:compile
[INFO] |  |  \- com.github.virtuald:curvesapi:jar:1.03:compile
[INFO] |  +- com.zhima.sdk:base:jar:1.0:compile
[INFO] |  +- com.alibaba:fastjson:jar:1.2.9:compile
[INFO] |  +- org.springframework.data:spring-data-redis:jar:1.6.2.RELEASE:compile
[INFO] |  +- redis.clients:jedis:jar:2.8.2:compile
[INFO] |  |  \- org.apache.commons:commons-pool2:jar:2.4.2:compile
[INFO] |  +- org.apache.httpcomponents:httpmime:jar:4.5.2:compile
[INFO] |  +- org.easyrules:easyrules-core:jar:2.3.0:compile
[INFO] |  +- org.easyrules:easyrules-spring:jar:2.3.0:compile
[INFO] |  +- org.easyrules:easyrules-quartz:jar:2.3.0:compile
[INFO] |  +- org.kie:kie-api:jar:6.5.0.Final:compile
[INFO] |  +- org.kie:kie-internal:jar:6.5.0.Final:compile
[INFO] |  +- org.kie:kie-spring:jar:6.5.0.Final:compile
[INFO] |  |  \- org.jbpm:jbpm-flow:jar:6.5.0.Final:compile
[INFO] |  |     \- joda-time:joda-time:jar:1.6.2:compile
[INFO] |  +- org.drools:drools-core:jar:6.5.0.Final:compile
[INFO] |  |  \- org.mvel:mvel2:jar:2.2.8.Final:compile
[INFO] |  +- org.drools:drools-compiler:jar:6.5.0.Final:compile
[INFO] |  |  +- org.antlr:antlr-runtime:jar:3.5:compile
[INFO] |  |  +- org.eclipse.jdt.core.compiler:ecj:jar:4.4.2:compile
[INFO] |  |  \- com.google.protobuf:protobuf-java:jar:2.6.0:compile
[INFO] |  +- org.drools:drools-jsr94:jar:6.5.0.Final:compile
[INFO] |  |  \- jsr94:jsr94:jar:1.1:compile
[INFO] |  +- org.drools:drools-decisiontables:jar:6.5.0.Final:compile
[INFO] |  |  \- org.drools:drools-templates:jar:6.5.0.Final:compile
[INFO] |  +- org.drools:knowledge-api:jar:6.5.0.Final:compile
[INFO] |  |  \- org.drools:drools-reteoo:jar:6.5.0.Final:compile
[INFO] |  \- com.aliyun.openservices:ons-client:jar:1.2.7.Final:compile
[INFO] +- com.orange.bjqianhai:bjqianhai-service:jar:0.0.1-SNAPSHOT:compile
[INFO] |  +- com.orange.bjqianhai:base-common-service:jar:0.0.1-SNAPSHOT:compile
[INFO] |  |  +- org.springframework.integration:spring-integration-sftp:jar:4.2.5.RELEASE:compile
[INFO] |  |  |  +- org.springframework.integration:spring-integration-file:jar:4.2.5.RELEASE:compile
[INFO] |  |  |  \- org.springframework.integration:spring-integration-stream:jar:4.2.5.RELEASE:compile
[INFO] |  |  +- com.sh.pay:base:jar:1.0:compile
[INFO] |  |  +- com.sh.encrypt:base:jar:1.0:compile
[INFO] |  |  +- com.google.guava:guava:jar:15.0:compile
[INFO] |  |  +- org.hibernate:hibernate-validator:jar:5.1.3.Final:compile
[INFO] |  |  |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |  |  +- org.jboss.logging:jboss-logging:jar:3.1.3.GA:compile
[INFO] |  |  |  \- com.fasterxml:classmate:jar:1.0.0:compile
[INFO] |  |  +- javax.el:javax.el-api:jar:2.2.4:compile
[INFO] |  |  +- org.glassfish.web:javax.el:jar:2.2.4:compile
[INFO] |  |  +- org.codehaus.xfire:xfire-core:jar:1.2.6:compile
[INFO] |  |  |  +- wsdl4j:wsdl4j:jar:1.6.1:compile
[INFO] |  |  |  +- stax:stax-api:jar:1.0.1:compile
[INFO] |  |  |  +- org.apache.ws.commons:XmlSchema:jar:1.1:compile
[INFO] |  |  |  \- org.codehaus.woodstox:wstx-asl:jar:3.2.0:compile
[INFO] |  |  +- org.codehaus.xfire:xfire-aegis:jar:1.2.6:compile
[INFO] |  |  |  \- net.java.dev.stax-utils:stax-utils:jar:20040917:compile
[INFO] |  |  +- org.bouncycastle:bcmail-jdk15on:jar:1.54:compile
[INFO] |  |  |  \- org.bouncycastle:bcpkix-jdk15on:jar:1.54:compile
[INFO] |  |  +- org.bouncycastle:bcpg-jdk15on:jar:1.54:compile
[INFO] |  |  +- org.bouncycastle:bcprov-jdk15on:jar:1.54:compile
[INFO] |  |  +- com.itextpdf.tool:xmlworker:jar:5.4.2:compile
[INFO] |  |  +- com.itextpdf:itextpdf:jar:5.4.2:compile
[INFO] |  |  +- com.jcraft:jsch:jar:0.1.53:compile
[INFO] |  |  +- com.aliyun.oss:aliyun-sdk-oss:jar:2.4.0:compile
[INFO] |  |  +- org.jsoup:jsoup:jar:1.10.1:compile
[INFO] |  |  +- org.apache.lucene:lucene-core:jar:5.5.4:compile
[INFO] |  |  +- org.apache.lucene:lucene-analyzers-common:jar:5.5.4:compile
[INFO] |  |  +- org.apache.lucene:lucene-queryparser:jar:5.5.4:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-queries:jar:5.5.4:compile
[INFO] |  |  |  \- org.apache.lucene:lucene-sandbox:jar:5.5.4:compile
[INFO] |  |  +- org.apache.lucene:lucene-highlighter:jar:5.5.4:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-join:jar:5.5.4:compile
[INFO] |  |  |  \- org.apache.lucene:lucene-memory:jar:5.5.4:compile
[INFO] |  |  +- com.chenlb.mmseg4j:mmseg4j-core:jar:1.10.0:compile
[INFO] |  |  +- com.chenlb.mmseg4j:mmseg4j-solr:jar:2.3.0:compile
[INFO] |  |  +- com.google.code.gson:gson:jar:2.2.4:compile
[INFO] |  |  +- com.squareup.okio:okio:jar:1.3.0:compile
[INFO] |  |  \- com.squareup.okhttp:okhttp:jar:2.3.0:compile
[INFO] |  +- com.orange.bjqianhai:base-business-service:jar:0.0.1-SNAPSHOT:compile
[INFO] |  \- com.orange.bjqianhai:base-capital-service:jar:0.0.1-SNAPSHOT:compile
[INFO] +- com.orange.bjqianhai:bjqianhai-model:jar:0.0.1-SNAPSHOT:compile
[INFO] +- com.orange.bjqianhai:bjqianhai-plan-model:jar:0.0.1-SNAPSHOT:compile
[INFO] |  +- net.sourceforge.htmlcleaner:htmlcleaner:jar:2.6.1:compile
[INFO] |  |  \- org.jdom:jdom2:jar:2.0.5:compile
[INFO] |  \- com.umpay.api:umpay:jar:1.0.1:compile
[INFO] +- com.orange.bjqianhai:testing:jar:0.0.1-SNAPSHOT:compile
[INFO] |  \- javax.annotation:jsr250-api:jar:1.0:compile
[INFO] +- junit:junit:jar:4.11:compile
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] +- javax.servlet:servlet-api:jar:2.5:provided
[INFO] +- com.novell.ldap:jldap:jar:4.3:compile
[INFO] +- jug:jug:jar:1.1.2:compile
[INFO] +- org.codehaus.groovy:groovy-all:jar:2.1.1:compile
[INFO] +- mysql:mysql-connector-java:jar:5.1.24:compile
[INFO] +- com.lowagie:itext:jar:2.1.0:compile
[INFO] |  +- bouncycastle:bcmail-jdk14:jar:136:compile
[INFO] |  \- bouncycastle:bcprov-jdk14:jar:136:compile
[INFO] +- org.xhtmlrenderer:core-renderer:jar:R8:compile
[INFO] +- org.apache.activemq:activemq-core:jar:5.7.0:compile
[INFO] |  +- org.apache.geronimo.specs:geronimo-jms_1.1_spec:jar:1.1.1:compile
[INFO] |  +- org.apache.activemq:kahadb:jar:5.7.0:compile
[INFO] |  +- org.apache.activemq.protobuf:activemq-protobuf:jar:1.1:compile
[INFO] |  +- org.fusesource.mqtt-client:mqtt-client:jar:1.3:compile
[INFO] |  |  +- org.fusesource.hawtdispatch:hawtdispatch-transport:jar:1.11:compile
[INFO] |  |  |  \- org.fusesource.hawtdispatch:hawtdispatch:jar:1.11:compile
[INFO] |  |  \- org.fusesource.hawtbuf:hawtbuf:jar:1.9:compile
[INFO] |  +- org.apache.geronimo.specs:geronimo-j2ee-management_1.1_spec:jar:1.0.1:compile
[INFO] |  +- commons-net:commons-net:jar:3.1:compile
[INFO] |  \- org.jasypt:jasypt:jar:1.9.0:compile
[INFO] +- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[INFO] \- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile

**Comment by wwwjljj** [comment]
我问了下我同事，他们说虽然jar包包了多次，但是不会出现类重复加载的情况。

**Comment by wu-sheng** [comment]
I can't find out a clue about how to trigger these exceptions. So, I have to ask you to provide a demo application which can reproduce these exceptions. Hop you can do this. Otherwise, I am not sure what I can do. @wwwjljj

**Comment by wu-sheng** [comment]
Support to enhance a class by multi plugins. So I am closing this issue. If other things come up, please submit a new issue.
