### ISSUE TITLE
Collector cluster mode fail, because of second round aggregation

### ISSUE THREAD

**Issue by wu-sheng** [OpenSkywalking/skywalking#551]
In 3.2.3, some literal strings are removed, by some buffer/cache mechanism. And the remote module didn't match that. That triggers this serious bug, collector can't run in collector mode.

**Comment by chidaodezhongsheng** [comment]
2017-10-26 17:33:12,423 - org.skywalking.apm.collector.stream.worker.RemoteWorkerRef -398406 [Thread-20] ERROR [] - null
java.lang.NullPointerException: null
        at org.skywalking.apm.collector.remote.grpc.proto.RemoteData$Builder.addDataStrings(RemoteData.java:1244) ~[apm-collector-remote-3.2.3-2017.jar:?]
        at org.skywalking.apm.collector.storage.define.noderef.NodeReferenceDataDefine.serialize(NodeReferenceDataDefine.java:74) ~[apm-collector-storage-3.2.3-2017.jar:?]
        at org.skywalking.apm.collector.stream.worker.RemoteWorkerRef.tell(RemoteWorkerRef.java:65) ~[apm-collector-stream-3.2.3-2017.jar:?]
        at org.skywalking.apm.collector.stream.worker.WorkerRefs.tell(WorkerRefs.java:55) ~[apm-collector-stream-3.2.3-2017.jar:?]
        at org.skywalking.apm.collector.stream.worker.impl.AggregationWorker.lambda$sendToNext$0(AggregationWorker.java:82) ~[apm-collector-stream-3.2.3-2017.jar:?]
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597) [?:1.8.0_144]
        at org.skywalking.apm.collector.stream.worker.impl.AggregationWorker.sendToNext(AggregationWorker.java:79) [apm-collector-stream-3.2.3-2017.jar:?]
        at org.skywalking.apm.collector.stream.worker.impl.AggregationWorker.onWork(AggregationWorker.java:56) [apm-collector-stream-3.2.3-2017.jar:?]
        at org.skywalking.apm.collector.stream.worker.AbstractWorker.execute(AbstractWorker.java:43) [apm-collector-stream-3.2.3-2017.jar:?]
        at org.skywalking.apm.collector.queue.disruptor.DisruptorEventHandler.onEvent(DisruptorEventHandler.java:59) [apm-collector-queue-3.2.3-2017.jar:?]
        at org.skywalking.apm.collector.queue.disruptor.DisruptorEventHandler.onEvent(DisruptorEventHandler.java:33) [apm-collector-queue-3.2.3-2017.jar:?]
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:129) [disruptor-3.3.6.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by wu-sheng** [comment]
Fix by #574, and released in 3.2.4
